#ifndef AUDUINO_HWDEFINES_h
#define AUDUINO_HWDEFINES_h

#define FALSE 0
#define TRUE 1

#define NUMBER_OF_KNOBS 5

#define NUMBER_OF_BUTTONS 8 
#define NUMBER_OF_DIODS 8

#define BUTTON_EDIT_MODE_INDEX 0
#define BUTTON_DISTORT_INDEX 1
#define BUTTON_RECORD_INDEX 2
#define BUTTON_INSTRUMENT_1_INDEX 3
#define BUTTON_INSTRUMENT_2_INDEX 4 
#define BUTTON_INSTRUMENT_3_INDEX 5
#define BUTTON_INSTRUMENT_4_INDEX 6

#define DIOD_EDIT_MODE_INDEX 0
#define DIOD_DISTORT_INDEX 1
#define DIOD_RECORD_INDEX 2
#define DIOD_INSTRUMENT_1_INDEX 3
#define DIOD_INSTRUMENT_2_INDEX 4
#define DIOD_INSTRUMENT_3_INDEX 5
#define DIOD_INSTRUMENT_4_INDEX 6
#define DIOD_MOON_INDEX 7

#define BUTTON_EDIT_MODE_PIN 11    
#define BUTTON_DISTORT_PIN 9
#define BUTTON_RECORD_PIN 10
#define BUTTON_INSTRUMENT_1_PIN 2
#define BUTTON_INSTRUMENT_2_PIN 4 
#define BUTTON_INSTRUMENT_3_PIN 8
#define BUTTON_INSTRUMENT_4_PIN 7
#define BUTTON_SHIFT_PIN 5

#define DIOD_EDIT_MODE_PIN  11
#define DIOD_DISTORT_PIN 9
#define DIOD_RECORD_PIN 10 
#define DIOD_INSTRUMENT_1_PIN 2
#define DIOD_INSTRUMENT_2_PIN 4 
#define DIOD_INSTRUMENT_3_PIN 8
#define DIOD_INSTRUMENT_4_PIN 7

/* Knob definitions */

#define KNOB_TOLERANCE 10
#define KNOB_FREEZE_DISTANCE 128

#define KNOB_1_PIN 0 
#define KNOB_2_PIN 1 
#define KNOB_3_PIN 2 
#define KNOB_4_PIN 3 
#define KNOB_5_PIN 4 

#define KNOB_1_INDEX 0
#define KNOB_2_INDEX 1
#define KNOB_3_INDEX 2
#define KNOB_4_INDEX 3 
#define KNOB_5_INDEX 4

#define KNOB_RECORD_TEMPO_INDEX 4 
#define KNOB_RECORD_LENGTH_INDEX 3
#define KNOB_RECORD_PATTERN_INDEX 2
#define KNOB_RECORD_VOL2_INDEX 1
#define KNOB_RECORD_VOL1_INDEX 0

#define KNOB_DISTORT_RATE_INDEX 4 
#define KNOB_DISTORT_AMT_INDEX 3
#define KNOB_DISTORT_PITCH_INDEX 2
#define KNOB_DISTORT_BITCRUSH_INDEX 1
#define KNOB_DISTORT_DEST_INDEX 0

#define KNOB_SYNTH_PARAM_INDEX 4
#define KNOB_SYNTH_CUT_INDEX 3
#define KNOB_SYNTH_DECAY_INDEX 2
#define KNOB_SYNTH_SAMPLE_INDEX 1
#define KNOB_SYNTH_VOLUME_INDEX 0


#define RADIO_NO_CONNECTION 255

#define RELEASE_BUTTON_BUFFER 10

#endif










